# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    # - python: 3.5
    #   dist: trusty
    #   sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true


install:
  - pip install -U tox-travis
  - pip install coveralls

script:
  #- tox
  - coverage run numsed/numsed.py --batch tests/test.batch

after_success:
  - coveralls
